### ISSUE TITLE
Autocomplete on "ENTER" does not works

### ISSUE THREAD

**Issue by BachiMjavanadze** [ironcutter24/cs-curly-formatter#3]
After installing your extension autocomplete on "ENTER" does not works. To make work autocomplete on "ENTER" instead of "TAB", I have this piece of code in my keybindings.json:

`  {
    "key": "tab",
    "command": "-acceptSelectedSuggestion",
    "when": "suggestWidgetVisible && textInputFocus"
  }`

**Comment by ghost** [comment]
The workaround from @BachiMjavanadze didn't work for me, but the following did:

- Go to File > Preferences > Keyboard Shortcuts
- Find "Curly Format"
- Right-Click > Change When Expression
- Append `&& !suggestWidgetVisible` to the expression

**Comment by icutter** [comment]
The issue has been addressed in version 0.0.7.
