### ISSUE TITLE
Cursor jumping

### ISSUE THREAD

**Issue by JoshZiv** [ironcutter24/cs-curly-formatter#5]
Whenever the code is formatted, the cursor jumps ahead a few lines or to the closing brace. This is making the extension very unusable.

**Comment by icutter** [comment]
Hi, do you have other formatter extensions enabled?
Have you tried disabling your extensions to figure out if any is conflicting with mine?

If this does not solve the problem, a gif/video of the issue would be helpful to figure out what is happening.

**Comment by JoshZiv** [comment]
Somehow, this could be a code issue, not the extension. I've checked out an old commit and I'm getting no problems. Formatting and building with dotnet shows no errors so I am lost as to what is causing the problem exactly.
I'll close this issue for now anyway since it seems like I'm the one who's done something wrong since the extension works perfectly fine on other code.

**Comment by icutter** [comment]
I'm glad your issue is solved.
If you're still willing to share a snapshot I could probably make the extension more robust to account for your use case too

**Comment by JoshZiv** [comment]
That'd be great but I have absolutely no idea what caused the issue. I've reintroduced the code in small chunks and the issue is now gone. Maybe I'd accidentally commented out/uncommented something by mistake or made a typo, or a number of other things.
Either way, I'm glad I can carry on using this extension, it's awesome.
