### ISSUE TITLE
File Area Jumps

### ISSUE THREAD

**Issue by holypeachy** [ironcutter24/cs-curly-formatter#6]
Type: <b>Bug</b>

I never had any problems until my file grew. I'm at around 1200 lines and I started to have the issue at around 1000 lines. When I would press enter to make a new line the caret would go jump a few lines down and to a "random" place in the code. This issue would also cause all my collapsed code to become uncollapsed and my code area/screen to jump down the file where I couldn't even see the caret. At first I thought it was a VS Code issue and when I thought about extensions that would alter such behavior this was the only one. I disabled it and the issue stopped, I enabled it again and it started.

Extension version: 0.0.7
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.86GB free)|
|Process Argv|--crash-reporter-id 24b2af10-fb17-45a2-b2ce-ea22a463eac8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30772539
pythonnocebcf:30776496

```

</details>

**Comment by icutter** [comment]
Would you mind sending me your code by email to reproduce? Meanwhile consider splitting it in smaller files, if possible.

**Comment by icutter** [comment]
I was not able to reproduce this issue, it's probably due to a conflict with other extensions.

**Comment by holypeachy** [comment]
I did some testing. It was Microsoft's C# extension to which the Formatter has a conflict with :/ Thanks for checking it out!
